# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-eks-spotinst-ocean-nodepool
  description: A terraform module to create an EKS node pool with Spot Ocean by Spot.io
  homepage: https://cloudposse.com/accelerate/
  topics: ""

